[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
b402_pool = "42a3hsCXtQLWonyxWZosaaCJCweYYKMrvNd25p1Jrt2y"
b402_verifier_transact = "Afjbnv2Ekxa98jjRw33xPPhZabevek2uZxoE75kr6ZrK"
b402_verifier_adapt_v2 = "DG7Fi75b2jkcUgG5K6Ekgpy7uigYxePPSxSSrdPzLGUd"
b402_jupiter_adapter = "3RHRcbinCmcj8JPBfVxb9FW76oh4r8y21aSx4JFy3yx7"

[programs.devnet]
b402_pool = "42a3hsCXtQLWonyxWZosaaCJCweYYKMrvNd25p1Jrt2y"
b402_verifier_transact = "Afjbnv2Ekxa98jjRw33xPPhZabevek2uZxoE75kr6ZrK"
b402_jupiter_adapter = "3RHRcbinCmcj8JPBfVxb9FW76oh4r8y21aSx4JFy3yx7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm --filter=@b402ai/solana-tests test"
