//! Canonical constants per PRD-02 and PRD-03.

pub const VERSION_PREFIX: &[u8] = b"b402/v1";

pub const SEED_CONFIG: &[u8] = b"config";
pub const SEED_TOKEN: &[u8] = b"token";
pub const SEED_VAULT: &[u8] = b"vault";
pub const SEED_TREE: &[u8] = b"tree";
pub const SEED_NULL: &[u8] = b"null";
pub const SEED_ADAPTERS: &[u8] = b"adapters";
pub const SEED_TREASURY: &[u8] = b"treasury";

pub const TREE_DEPTH: usize = 26;
/// Size of the recent-root ring buffer. The SDK must generate a proof fast
/// enough that the proof's `merkleRoot` is still within the last
/// `ROOT_HISTORY_SIZE` appends when the tx lands on-chain, or the pool will
/// reject with `InvalidMerkleRoot`.
///
/// 128 gives comfortable headroom for bursty usage: at 10 shields/sec a proof
/// has ~13s to generate+submit before becoming stale. Up from 64 (a ~6s window
/// at the same burst rate) — matches the 2026-04-23 review finding.
pub const ROOT_HISTORY_SIZE: usize = 128;

/// Canonical BN254-Fr encodings of the domain tags (little-endian 32 bytes).
/// These match `packages/crypto` and the `circuits/` compile. The program
/// checks public inputs against these values on every verify call.
///
/// The Fr value is computed as: UTF-8 bytes of tag interpreted as
/// big-endian integer, reduced mod p. See `packages/crypto/src/fr.rs`.
///
/// Values here are generated by `scripts/generate-tag-constants.ts` which
/// reads PRD-02 §1.2 and produces this file. Changing a tag string breaks
/// every existing commitment and nullifier.
pub const TAG_COMMIT: [u8; 32] = tag_fr_le(b"b402/v1/commit");
pub const TAG_NULLIFIER: [u8; 32] = tag_fr_le(b"b402/v1/null");
pub const TAG_MK_NODE: [u8; 32] = tag_fr_le(b"b402/v1/mk-node");
pub const TAG_MK_ZERO: [u8; 32] = tag_fr_le(b"b402/v1/mk-zero");
pub const TAG_SPEND_KEY_PUB: [u8; 32] = tag_fr_le(b"b402/v1/spend-key-pub");
pub const TAG_FEE_BIND: [u8; 32] = tag_fr_le(b"b402/v1/fee-bind");
pub const TAG_ROOT_BIND: [u8; 32] = tag_fr_le(b"b402/v1/root-bind");
pub const TAG_ADAPT_BIND: [u8; 32] = tag_fr_le(b"b402/v1/adapt-bind");
pub const TAG_RECIPIENT_BIND: [u8; 32] = tag_fr_le(b"b402/v1/recipient-bind");

/// Encode a tag string to its canonical 32-byte LE Fr representation.
///
/// The tag is interpreted as a big-endian integer. Since tags are ≤ 31 bytes,
/// the resulting integer is always < p, so no reduction is necessary.
/// We produce the LE byte encoding by reversing.
const fn tag_fr_le(tag: &[u8]) -> [u8; 32] {
    assert!(tag.len() <= 31, "domain tag must be ≤ 31 bytes");
    // Build big-endian 32-byte representation: pad front with zeros, tag at end.
    let mut be = [0u8; 32];
    let offset = 32 - tag.len();
    let mut i = 0;
    while i < tag.len() {
        be[offset + i] = tag[i];
        i += 1;
    }
    // Reverse to little-endian.
    let mut le = [0u8; 32];
    let mut j = 0;
    while j < 32 {
        le[j] = be[31 - j];
        j += 1;
    }
    le
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tags_are_distinct() {
        let all = [
            TAG_COMMIT,
            TAG_NULLIFIER,
            TAG_MK_NODE,
            TAG_MK_ZERO,
            TAG_SPEND_KEY_PUB,
            TAG_FEE_BIND,
            TAG_ROOT_BIND,
            TAG_ADAPT_BIND,
            TAG_RECIPIENT_BIND,
        ];
        for i in 0..all.len() {
            for j in (i + 1)..all.len() {
                assert_ne!(all[i], all[j], "tag collision at {} and {}", i, j);
            }
        }
    }

    #[test]
    fn tag_encoding_matches_spec() {
        // "b402/v1/commit" in BE then reversed to LE.
        // First byte of BE is 'b' (0x62) at position 32 - 14 = 18.
        // So be[18] = 0x62, which becomes le[31 - 18] = le[13] = 0x62.
        let t = TAG_COMMIT;
        assert_eq!(t[13], b'b');
        assert_eq!(t[12], b'4');
        assert_eq!(t[0], b't'); // last char of "b402/v1/commit" is 't' at be[31] → le[0]
    }
}
