#!/usr/bin/env bash
# Boot a mainnet-fork harness for v2 testing.
#
# What this loads:
#   - Light Protocol programs (bundled with the Light CLI; fresh trees,
#     no mainnet compressed-account state needed for our tests).
#   - Our 4 core programs at their declare_id! addresses, loaded from
#     target/deploy/*.so. These are NOT on mainnet yet, so we deploy
#     them locally at the canonical IDs the SDK + tests already use.
#   - Jupiter v6 program cloned from mainnet (for swap tests)
#   - Kamino lending program cloned from mainnet (for lend tests)
#   - USDC mainnet mint cloned (for swap input/output token)
#
# Photon indexer + Light prover are launched alongside by `light test-validator`.
#
# Note: --mainnet flag would try to clone Light's existing compressed-account
# state via getProgramAccounts, which the public mainnet RPC rejects. Our
# tests don't need that state — they create fresh nullifiers/notes — so we
# use the default (local Light infra + fresh trees) and clone only the
# external programs we need via --validator-args.
#
# Usage:
#   tests/v2/scripts/start-mainnet-fork.sh
#
# Stop:
#   light test-validator --stop

set -euo pipefail

# Repo root resolves regardless of cwd.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# --- Our programs (declare_id! values, must match SDK constants) ---
POOL_ID="42a3hsCXtQLWonyxWZosaaCJCweYYKMrvNd25p1Jrt2y"
NULLIFIER_ID="2AnRZwWu6CTurZs1yQpqrcJWo4yRYL1xpeV78b2siweq"
VERIFIER_TRANSACT_ID="Afjbnv2Ekxa98jjRw33xPPhZabevek2uZxoE75kr6ZrK"
VERIFIER_ADAPT_ID="3Y2tyhNSaUiW5AcZcmFGRyTMdnroxHxc5GqFQPcMTZae"
MOCK_ADAPTER_ID="89kw33YDcbXfiayVNauz599LaDm51EuU8amWydpjYKgp"
JUPITER_ADAPTER_ID="3RHRcbinCmcj8JPBfVxb9FW76oh4r8y21aSx4JFy3yx7"
KAMINO_ADAPTER_ID="2enwFgcGKJDqruHpCtvmhtxe3DYcV3k72VTvoGcdt2rX"

# --- External programs to clone from mainnet ---
# Jupiter V6 (swap aggregator)
JUPITER_V6="JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"
# Kamino Lending program
KAMINO_LEND="KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD"
# Mainnet USDC mint (used as the swap input/output token + test mint)
USDC_MINT="EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"

# Sanity: all .so files we need.
POOL_SO="$ROOT/target/deploy/b402_pool.so"
NULLIFIER_SO="$ROOT/programs/b402-nullifier/target/deploy/b402_nullifier.so"
VERIFIER_TRANSACT_SO="$ROOT/target/deploy/b402_verifier_transact.so"
VERIFIER_ADAPT_SO="$ROOT/target/deploy/b402_verifier_adapt.so"
MOCK_ADAPTER_SO="$ROOT/target/deploy/b402_mock_adapter.so"
JUPITER_ADAPTER_SO="$ROOT/target/deploy/b402_jupiter_adapter.so"
KAMINO_ADAPTER_SO="$ROOT/target/deploy/b402_kamino_adapter.so"

for f in "$POOL_SO" "$NULLIFIER_SO" "$VERIFIER_TRANSACT_SO" "$VERIFIER_ADAPT_SO" "$MOCK_ADAPTER_SO" "$JUPITER_ADAPTER_SO" "$KAMINO_ADAPTER_SO"; do
  if [[ ! -f "$f" ]]; then
    echo "FAIL: missing $f — run 'anchor build' (and rebuild b402-nullifier separately)." >&2
    exit 1
  fi
done

# Upgrade authority for our programs. Reuse the local CLI default keypair.
UPGRADE_AUTH="$HOME/.config/solana/id.json"
if [[ ! -f "$UPGRADE_AUTH" ]]; then
  echo "FAIL: $UPGRADE_AUTH missing — set up Solana CLI keypair first." >&2
  exit 1
fi

# Optional: Kamino state. If /tmp/kamino-clone.json exists (generated by
# ops/kamino-clone.ts), clone every account it lists via --clone passthrough.
# That gives us real Kamino reserve, lending market, vaults, and oracle
# accounts on the fork — required for v2_fork_lend tests that exercise
# kamino_adapter through pool::adapt_execute.
KAMINO_CLONE_FILE="${KAMINO_CLONE_FILE:-/tmp/kamino-clone.json}"
KAMINO_CLONE_ARGS=""
# Pubkeys solana-test-validator already has built-in. Trying to --clone any
# of these silently aborts the validator at startup with exit code 1.
BUILTINS="11111111111111111111111111111111 BPFLoaderUpgradeab1e11111111111111111111111 TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL ComputeBudget111111111111111111111111111111 Sysvar1nstructions1111111111111111111111111 SysvarRent111111111111111111111111111111111"
is_builtin() {
  for b in $BUILTINS; do [[ "$1" == "$b" ]] && return 0; done
  return 1
}
if [[ -f "$KAMINO_CLONE_FILE" ]]; then
  echo "    cloning Kamino state: $KAMINO_CLONE_FILE"
  for p in $(jq -r '.programs[]?' "$KAMINO_CLONE_FILE"); do
    if is_builtin "$p"; then echo "    (skip builtin program $p)"; continue; fi
    KAMINO_CLONE_ARGS="$KAMINO_CLONE_ARGS --clone-upgradeable-program $p"
  done
  # NOTE: light test-validator's --validator-args forwarding has a bug above
  # ~7 --clone flags (validator silently exits 1; photon also breaks at 8).
  # Direct solana-test-validator handles 16+ fine. Until we drop the light
  # wrapper (Phase 7 task A), cap at the first 7 data accounts: market,
  # reserve, marketAuth, plus the 4 most-essential reserve-referenced
  # accounts (liquiditySupply, kUSDC mint, collateral vault, USDC mint).
  KAMINO_DATA_LIMIT="${KAMINO_DATA_LIMIT:-7}"
  count=0
  for d in $(jq -r '.data[]?' "$KAMINO_CLONE_FILE"); do
    if is_builtin "$d"; then echo "    (skip builtin account $d)"; continue; fi
    if [[ $count -ge $KAMINO_DATA_LIMIT ]]; then
      echo "    (skip $d — past KAMINO_DATA_LIMIT=$KAMINO_DATA_LIMIT)"
      continue
    fi
    KAMINO_CLONE_ARGS="$KAMINO_CLONE_ARGS --clone $d"
    count=$((count + 1))
  done
fi

echo "==> stopping any previous test-validator"
light test-validator --stop || true

echo "==> starting mainnet-forked test-validator + Photon"
echo "    LOAD_AT_BOOT=${LOAD_AT_BOOT:-pool,nullifier,verifier_adapt,kamino_adapter}"
echo "    KAMINO_CLONE_FILE=$KAMINO_CLONE_FILE (data limit=${KAMINO_DATA_LIMIT:-7})"

# --validator-args is forwarded verbatim. --clone-upgradeable-program clones
# the program AND its program-data account (cheaper than two --clone calls).
# --url mainnet-beta tells the underlying solana-test-validator where to
# clone from (Light Labs's --mainnet flag handles Light's accounts already).
# Light test-validator's --validator-args has a hard total-arg-length cap.
# When KAMINO_CLONE_ARGS is full (7+ data accounts), the wrapper drops the
# excess silently and the validator fails. Workaround: only load CRITICAL
# programs at boot; the rest are deployed after fork is up via
# `solana program deploy`. Critical = pool + nullifier + verifier_adapt
# (everything else loaded post-boot).
LOAD_AT_BOOT="${LOAD_AT_BOOT:-pool,nullifier,verifier_adapt,kamino_adapter}"
BOOT_ARGS=""
if [[ ",$LOAD_AT_BOOT," == *",pool,"* ]]; then BOOT_ARGS="$BOOT_ARGS --upgradeable-program $POOL_ID $POOL_SO $UPGRADE_AUTH"; fi
if [[ ",$LOAD_AT_BOOT," == *",nullifier,"* ]]; then BOOT_ARGS="$BOOT_ARGS --upgradeable-program $NULLIFIER_ID $NULLIFIER_SO $UPGRADE_AUTH"; fi
if [[ ",$LOAD_AT_BOOT," == *",verifier_transact,"* ]]; then BOOT_ARGS="$BOOT_ARGS --upgradeable-program $VERIFIER_TRANSACT_ID $VERIFIER_TRANSACT_SO $UPGRADE_AUTH"; fi
if [[ ",$LOAD_AT_BOOT," == *",verifier_adapt,"* ]]; then BOOT_ARGS="$BOOT_ARGS --upgradeable-program $VERIFIER_ADAPT_ID $VERIFIER_ADAPT_SO $UPGRADE_AUTH"; fi
if [[ ",$LOAD_AT_BOOT," == *",mock_adapter,"* ]]; then BOOT_ARGS="$BOOT_ARGS --upgradeable-program $MOCK_ADAPTER_ID $MOCK_ADAPTER_SO $UPGRADE_AUTH"; fi
if [[ ",$LOAD_AT_BOOT," == *",jupiter_adapter,"* ]]; then BOOT_ARGS="$BOOT_ARGS --upgradeable-program $JUPITER_ADAPTER_ID $JUPITER_ADAPTER_SO $UPGRADE_AUTH"; fi
if [[ ",$LOAD_AT_BOOT," == *",kamino_adapter,"* ]]; then BOOT_ARGS="$BOOT_ARGS --upgradeable-program $KAMINO_ADAPTER_ID $KAMINO_ADAPTER_SO $UPGRADE_AUTH"; fi

# Trim leading/trailing whitespace + collapse internal spaces. Empty
# arguments crash solana-test-validator with "Found argument '' which
# wasn't expected" — that was the actual bug masking everything else.
VALIDATOR_ARGS=$(echo "--url mainnet-beta $KAMINO_CLONE_ARGS" | tr -s ' ' | sed 's/^ //;s/ $//')

light test-validator $BOOT_ARGS \
  --validator-args "$VALIDATOR_ARGS"
