#!/usr/bin/env bash
# Boot the mainnet-fork validator with everything needed to test the
# Token-2022 + transferHook end-to-end flow against pump.fun's $PUMP.
#
# What this clones from mainnet on top of the standard fork harness:
#   - PUMP mint (pumpCmXqMfrsAkQ5r49WcJnRayYRqmXz6ae8H7H9Dfn) — Token-2022,
#     has transferHook + transferFee extensions.
#   - PUMP's transfer-hook program (read from the mint's extension data).
#   - PUMP's ExtraAccountMetaList PDA: derive from the hook program +
#     mint via [b"extra-account-metas", mint.toBytes()].
#   - Whatever extra accounts the hook references (read from the
#     ExtraAccountMetaList TLV; usually 1-4 account metas).
#   - Jupiter route accounts for wSOL → PUMP (Quantum → SolFi V2 per
#     current routing). Generated by ops/jup-quote.ts.
#
# Usage:
#   tests/v2/scripts/start-pump-fork.sh
#
# Prereqs:
#   1. anchor build -p b402-pool --no-idl
#   2. anchor build -p b402-jupiter-adapter --no-idl
#   3. cargo build-sbf --manifest-path programs/b402-nullifier/Cargo.toml
#   4. Solana CLI keypair at ~/.config/solana/id.json
#   5. light test-validator installed (npm i -g @lightprotocol/zk-compression-cli)
#   6. solana CLI with mainnet access (for cloning accounts)
#
# Stop:
#   light test-validator --stop
#
# After it's running, run the swap test in another terminal:
#   pnpm --filter @b402ai/solana-examples tsx examples/swap-e2e-pump.ts

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

PUMP_MINT="pumpCmXqMfrsAkQ5r49WcJnRayYRqmXz6ae8H7H9Dfn"
JUPITER_V6="JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"
USDC="EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
WSOL="So11111111111111111111111111111111111111112"

MAINNET_RPC="${MAINNET_RPC:-https://api.mainnet-beta.solana.com}"

echo "==> 0. Pre-flight: ensure required .so files exist"
for f in \
  "$ROOT/target/deploy/b402_pool.so" \
  "$ROOT/target/deploy/b402_jupiter_adapter.so"; do
  [[ -f "$f" ]] || { echo "MISSING: $f — run anchor build first"; exit 1; }
done
echo "    OK: pool.so + jupiter_adapter.so present"

echo
echo "==> 1. Fetch a real Jupiter route wSOL → PUMP (1 SOL test size)"
ROUTE_FILE="${ROUTE_FILE:-/tmp/pump-route.json}"
if [[ ! -f "$ROUTE_FILE" ]] || [[ "${REFRESH_ROUTE:-0}" == "1" ]]; then
  TEST_CALLER="${TEST_CALLER:-$(solana address)}"
  pnpm --filter @b402ai/solana-tools tsx ops/jup-quote.ts \
    --in  "$WSOL" \
    --out "$PUMP_MINT" \
    --amount 1000000000 \
    --caller "$TEST_CALLER" \
    --out-file "$ROUTE_FILE" || {
      echo "    Jupiter quote failed — pump may not have a route right now."
      echo "    Try a different mint or check pump.fun liquidity."
      exit 1
    }
fi
echo "    Route saved: $ROUTE_FILE"

echo
echo "==> 2. Resolve PUMP's transfer-hook extras (hook program + ExtraAccountMetaList + extras)"
# Read PUMP mint -> find hook program from extension TLV -> derive
# ExtraAccountMetaList PDA -> read its data -> collect all referenced accounts.
HOOK_INFO_FILE="${HOOK_INFO_FILE:-/tmp/pump-hook.json}"
pnpm --filter @b402ai/solana-tools tsx "$SCRIPT_DIR/resolve-transfer-hook.ts" \
  --mint "$PUMP_MINT" \
  --rpc  "$MAINNET_RPC" \
  --out-file "$HOOK_INFO_FILE" || {
    echo "    Hook resolution failed — see error above."
    exit 1
  }
echo "    Hook info: $HOOK_INFO_FILE"

echo
echo "==> 3. Build the full clone list for the fork validator"
CLONE_ARGS=""
# Standard external programs
for p in "$JUPITER_V6"; do
  CLONE_ARGS="$CLONE_ARGS --clone-upgradeable-program $p"
done
# Standard mints
for m in "$USDC" "$WSOL" "$PUMP_MINT"; do
  CLONE_ARGS="$CLONE_ARGS --clone $m"
done
# Hook program + ExtraAccountMetaList + every extra-meta account
HOOK_PROGRAM=$(jq -r '.hookProgram' "$HOOK_INFO_FILE")
EXTRA_META_PDA=$(jq -r '.extraAccountMetasPda' "$HOOK_INFO_FILE")
CLONE_ARGS="$CLONE_ARGS --clone-upgradeable-program $HOOK_PROGRAM"
CLONE_ARGS="$CLONE_ARGS --clone $EXTRA_META_PDA"
for a in $(jq -r '.extraAccounts[]?' "$HOOK_INFO_FILE"); do
  CLONE_ARGS="$CLONE_ARGS --clone $a"
done
# Jupiter route accounts
for a in $(jq -r '.clone[]?' "$ROUTE_FILE"); do
  CLONE_ARGS="$CLONE_ARGS --clone $a"
done

echo "    Clone count: $(echo "$CLONE_ARGS" | wc -w | tr -d ' ') flags"
echo "    Hook program: $HOOK_PROGRAM"
echo "    ExtraAccountMetaList PDA: $EXTRA_META_PDA"

echo
echo "==> 4. Stop any prior validator"
light test-validator --stop >/dev/null 2>&1 || true

echo
echo "==> 5. Boot test-validator + Photon with PUMP fork state"
# LOAD_AT_BOOT picks which .so files get deployed at the canonical IDs.
# For PUMP swap test we need pool + jupiter_adapter + verifier_* + nullifier.
LOAD_AT_BOOT="pool,jupiter_adapter,verifier_transact,verifier_adapt,nullifier" \
EXTRA_CLONE_ARGS="$CLONE_ARGS" \
  "$SCRIPT_DIR/start-mainnet-fork.sh"
